docman/document/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class CreateDocument(FlaskForm):
    """
    Form for users to create new document
    """
    title = StringField('Title', validators=[DataRequired()])
    access = SelectField('Access',
                         choices=[('public', 'Public'), ('private', 'Private'), ('role', 'Role')],
                         validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Submit')

docman/document/__init__.py
from flask import Blueprint

document = Blueprint('document', __name__)

from . import views

docman/document/views.py
from flask import flash, url_for, redirect, render_template
from flask_login import login_required, current_user
from . import document
from .forms import CreateDocument
from sqlalchemy import desc, and_, or_, not_, select

from .. import db
from ..models import Document, User, Role


@document.route('/document/create', methods=['GET', 'POST'])
@login_required
def create():
    """
    Handles requests to the /create route
    :return: login or register page
    """
    add_document = True
    form = CreateDocument()
    if form.validate_on_submit():
        print('Current User ID', current_user.id)
        new_document = Document(
            title=form.title.data,
            access=form.access.data,
            content=form.content.data,
            user_id=current_user.id,
        )

        # add document to database
        db.session.add(new_document)
        db.session.commit()

        flash('You have created a new document.')

        return redirect(url_for('document.get_documents'))

    return render_template('document/create.html', title='Create Document', form=form, add_document=add_document)


@document.route('/documents')
@login_required
def get_documents():
    """
    Get all documents the user is permitted to view
    :return: documents page
    """
    same_role = User.query.filter_by(role_id=current_user.role_id).all()
    same_role_list = [user.id for user in same_role]

    documents = db.session.query(Document).join("user", "role"). \
        filter(or_(Document.access == 'public',
                   Document.user_id == current_user.id,
                   (and_(Document.access == 'role', Document.user_id.in_(same_role_list))))). \
        order_by(desc(Document.created_at)).all()

    return render_template('document/documents.html', documents=documents, title='All Documents')


def my_documents(id):
    """
    :return: the documents of the user
    """
    documents = db.session.query(Document). \
        filter(Document.user_id == id). \
        order_by(desc(Document.created_at)).all()
    return documents


@document.route('/documents/me')
@login_required
def get_my_documents():
    """
    Get all documents owned by the user
    :return: my documents page
    """
    documents = my_documents(current_user.id)

    return render_template('document/documents.html', documents=documents, title='My Documents')


@document.route('/document/<int:id>', methods=['GET'])
@login_required
def get_document(id):
    """
    Opens up a document
    :param id: the document id
    :return: the single document page
    """
    doc = Document.query.get_or_404(id)

    return render_template('document/document.html', document=doc, title="Single Document")


@document.route('/document/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_document(id):
    """
    Edit a document
    :param id: document id to be edited
    :return: the documents page
    """
    add_document = False
    document_to_edit = Document.query.get_or_404(id)
    form = CreateDocument(obj=document_to_edit)
    if form.validate_on_submit():
        document_to_edit.title = form.title.data
        document_to_edit.access = form.access.data
        document_to_edit.content = form.content.data
        try:
            db.session.add(document_to_edit)
            db.session.commit()
            flash('You have successfully edited a document')
        except:
            flash('Error: Document title already exists')

        return redirect(url_for('document.get_document', id=document_to_edit.id))

    form.title.data = document_to_edit.title
    form.access.data = document_to_edit.access
    form.content.data = document_to_edit.content
    return render_template('document/create.html', form=form, title="Edit Document", add_document=add_document)


@document.route('/document/delete/<int:id>', methods=['GET'])
@login_required
def delete_document(id):
    """
    Delete a document
    :param id: id of the document
    """
    doc = Document.query.get_or_404(id)
    if doc.user_id == current_user.id:
        db.session.delete(doc)
        db.session.commit()
        flash('You have deleted a document')

        return redirect(url_for('document.get_documents'))

    flash('You do not have permission to delete this document')
    return redirect(url_for('document.get_documents'))

docman/templates/document/create.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Create Document{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
            {% if add_document %}
            <h1>Create New Document</h1>
            {% else %}
            <h1>Edit Document</h1>
            {% endif %}
            <br/>
            {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

docman/templates/document/document.html
{% extends "base.html" %}
{% block title %}Document{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <h1 style="text-align:center;">{{document.title}}</h1>
          <small>{{document.access}}</small>
        <p>{{document.content}}</p>
      </div>
      <div>
        <a href="{{url_for('document.edit_document', id=document.id)}}" class="btn btn-info">
          <i class="fa fa-pencil"></i>
          Edit Document
        </a>
        <a type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal">
          <i class="fa fa-trash"></i>
          Delete Document
        </a>
      </div>

      <!-- Modal -->
        <div id="myModal" class="modal fade" role="dialog">
          <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Confirm delete</h4>
              </div>
              <div class="modal-body">
                <p>Are you sure you want to delete this document?</p>
              </div>
              <div class="modal-footer">
                <a href="{{url_for('document.delete_document', id=document.id)}}" class="btn btn-danger">Yes, delete</a>
                <a type="button" class="btn btn-default" data-dismiss="modal">Cancel</a>
              </div>
            </div>

          </div>
        </div>

    </div>
  </div>
</div>
{% endblock %}

docman/templates/document/documents.html
{% extends "base.html" %}
{% block title %}Documents{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <h1 style="text-align:center;">All Documents</h1>
        {% if documents %}
          <hr class="intro-divider">
          <div class="container">
              <div class="row">
              {% for document in documents %}
              <div class="document col-sm-6 col-md-4 col-lg-3">
                  <div class="document-card">
                      <div class="card-container">
                        <h3><b>{{document.title | truncate(25, True)}}</b></h3>
                          <hr>
                          <div class="card-content">
                              <p>{{document.content | truncate(120)}}</p>
                          </div>
                      </div>
                      <div class="card-actions">
                          <span>{{document.user.username}}</span>
                          <a href="{{url_for('document.get_document', id=document.id)}}">READ</a>
                      </div>
                  </div>
              </div>
              {% endfor %}
              </div>
          </div>
        {% else %}
          <div class="documents-">
            <h3> No documents have been added. </h3>
            <hr class="intro-divider">
        {% endif %}
          </div>
          <a href="{{ url_for('document.create') }}" class="center-element btn btn-default btn-lg">
            <i class="fa fa-plus"></i>
            New Document
          </a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

docman/templates/document/my_documents.html
{% extends "document/document.html" %}